# Generated by Django 4.0 on 2021-12-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('distance', models.FloatField(verbose_name='Расстояние')),
            ],
        ),
    ]
